### ISSUE TITLE
String Index out of range: -1 error

### ISSUE THREAD

**Issue by dax-dot-gay** [DomAmato/Robot#2]
I'm not altogether sure whether this is a bug with your mod or just with incompatibility issues (although based on my Python knowledge an IndexError is generally not a good thing :) ), but I'm not sure how to resolve this issue.

Crash report:
[Pastebin](https://pastebin.com/AXDWXfFN)

Thanks!
-iTecAI

**Comment by DomAmato** [comment]
Looks like an error on my end I will try to resolve quickly thanks for the error output message

**Comment by dax-dot-gay** [comment]
Thanks! :)

**Comment by DomAmato** [comment]
ok the newest version should fix your issue.
