### ISSUE TITLE
Itemnames with numbers

### ISSUE THREAD

**Issue by dani154** [DomAmato/Robot#4]
Throws "Syntax Invalid" when there are Itemnames with Numbers at the start.

**Comment by DomAmato** [comment]
Can you be more clean when this happens? Is this during the enumeration step when it first boots up the game and logs all the different registered items or is it at some other point when this happens?

**Comment by dani154** [comment]
Ingame in the robot GUI.

When you import the api.robot from ingame commandline you get "Syntax Invalid" in the Items.py file.

**Comment by DomAmato** [comment]
should be fixed with commit f77ee4140e928a668ed4ab61b95c863b2eeaa15b
